# YAML configuration file with some sensible defaults, except Reddit app secrets.
# Each value can be overwritten by a custom YAML file which path is under "CUSTOM_SETTINGS_PATH"
# environment variable.
# In this custom YAML you don't need to specify all parameters, if a parameter is absent in the
# custom one a default value from this file will be used.

api:
  # Host where API will listen to requests
  host: 0.0.0.0
  # Port where API will listen to requests
  port: 8080
  authorization_header:
    # Name of authorization header, or empty for public access
    name:
    # Expected value of authorization header, or empty for public access
    expected_value:
reddit:
  client:
    # Reddit dev app ID used by Reddit client
    id:
    # Reddit dev app secret used by Reddit client
    secret:
    # User agent used by Reddit client
    user_agent: Reddit API API (by Electronic-Mango on GitHub)
